client_id = "2b8e6fdb5104ecbbfb5820eb32e312fa"
name = "Wishlist-247"
application_url = "https://YOUR-LIVE-APP-URL.com"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-04"

[[webhooks.subscriptions]]
topics = ["app/uninstalled"]
uri = "/webhooks/app/uninstalled"

[[webhooks.subscriptions]]
topics = ["app/scopes_update"]
uri = "/webhooks/app/scopes_update"

[access_scopes]
scopes = "write_products,write_app_proxy"

[auth]
redirect_urls = [
  "https://YOUR-LIVE-APP-URL.com/api/auth",
  "https://YOUR-LIVE-APP-URL.com/auth/callback",
  "https://YOUR-LIVE-APP-URL.com/api/auth/callback"
]

[app_proxy]
url = "/proxy"
prefix = "apps"
subpath = "wishlist"